// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/bitset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BSCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *BSCreateRequest) Reset() {
	*x = BSCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCreateRequest) ProtoMessage() {}

func (x *BSCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCreateRequest.ProtoReflect.Descriptor instead.
func (*BSCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{0}
}

func (x *BSCreateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSCreateRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BSCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BSCreateResponse) Reset() {
	*x = BSCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCreateResponse) ProtoMessage() {}

func (x *BSCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCreateResponse.ProtoReflect.Descriptor instead.
func (*BSCreateResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{1}
}

func (x *BSCreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BSDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *BSDelRequest) Reset() {
	*x = BSDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSDelRequest) ProtoMessage() {}

func (x *BSDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSDelRequest.ProtoReflect.Descriptor instead.
func (*BSDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{2}
}

func (x *BSDelRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type BSDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BSDelResponse) Reset() {
	*x = BSDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSDelResponse) ProtoMessage() {}

func (x *BSDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSDelResponse.ProtoReflect.Descriptor instead.
func (*BSDelResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{3}
}

func (x *BSDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BSSetRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   uint32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Value bool   `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BSSetRangeRequest) Reset() {
	*x = BSSetRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSSetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSSetRangeRequest) ProtoMessage() {}

func (x *BSSetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSSetRangeRequest.ProtoReflect.Descriptor instead.
func (*BSSetRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{4}
}

func (x *BSSetRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSSetRangeRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BSSetRangeRequest) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *BSSetRangeRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type BSSetRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BSSetRangeResponse) Reset() {
	*x = BSSetRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSSetRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSSetRangeResponse) ProtoMessage() {}

func (x *BSSetRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSSetRangeResponse.ProtoReflect.Descriptor instead.
func (*BSSetRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{5}
}

func (x *BSSetRangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BSMSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bits  []uint32 `protobuf:"varint,2,rep,packed,name=bits,proto3" json:"bits,omitempty"`
	Value bool     `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BSMSetRequest) Reset() {
	*x = BSMSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSMSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSMSetRequest) ProtoMessage() {}

func (x *BSMSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSMSetRequest.ProtoReflect.Descriptor instead.
func (*BSMSetRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{6}
}

func (x *BSMSetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSMSetRequest) GetBits() []uint32 {
	if x != nil {
		return x.Bits
	}
	return nil
}

func (x *BSMSetRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type BSMSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BSMSetResponse) Reset() {
	*x = BSMSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSMSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSMSetResponse) ProtoMessage() {}

func (x *BSMSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSMSetResponse.ProtoReflect.Descriptor instead.
func (*BSMSetResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{7}
}

func (x *BSMSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BSGetRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   uint32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *BSGetRangeRequest) Reset() {
	*x = BSGetRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSGetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSGetRangeRequest) ProtoMessage() {}

func (x *BSGetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSGetRangeRequest.ProtoReflect.Descriptor instead.
func (*BSGetRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{8}
}

func (x *BSGetRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSGetRangeRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BSGetRangeRequest) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type BSGetRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []bool `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *BSGetRangeResponse) Reset() {
	*x = BSGetRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSGetRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSGetRangeResponse) ProtoMessage() {}

func (x *BSGetRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSGetRangeResponse.ProtoReflect.Descriptor instead.
func (*BSGetRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{9}
}

func (x *BSGetRangeResponse) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type BSMGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bits []uint32 `protobuf:"varint,2,rep,packed,name=bits,proto3" json:"bits,omitempty"`
}

func (x *BSMGetRequest) Reset() {
	*x = BSMGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSMGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSMGetRequest) ProtoMessage() {}

func (x *BSMGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSMGetRequest.ProtoReflect.Descriptor instead.
func (*BSMGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{10}
}

func (x *BSMGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSMGetRequest) GetBits() []uint32 {
	if x != nil {
		return x.Bits
	}
	return nil
}

type BSMGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []bool `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *BSMGetResponse) Reset() {
	*x = BSMGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSMGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSMGetResponse) ProtoMessage() {}

func (x *BSMGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSMGetResponse.ProtoReflect.Descriptor instead.
func (*BSMGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{11}
}

func (x *BSMGetResponse) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type BSCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *BSCountRequest) Reset() {
	*x = BSCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCountRequest) ProtoMessage() {}

func (x *BSCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCountRequest.ProtoReflect.Descriptor instead.
func (*BSCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{12}
}

func (x *BSCountRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type BSCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BSCountResponse) Reset() {
	*x = BSCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCountResponse) ProtoMessage() {}

func (x *BSCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCountResponse.ProtoReflect.Descriptor instead.
func (*BSCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{13}
}

func (x *BSCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BSCountRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   uint32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *BSCountRangeRequest) Reset() {
	*x = BSCountRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCountRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCountRangeRequest) ProtoMessage() {}

func (x *BSCountRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCountRangeRequest.ProtoReflect.Descriptor instead.
func (*BSCountRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{14}
}

func (x *BSCountRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BSCountRangeRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BSCountRangeRequest) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type BSCountRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BSCountRangeResponse) Reset() {
	*x = BSCountRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BSCountRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSCountRangeResponse) ProtoMessage() {}

func (x *BSCountRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_bitset_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSCountRangeResponse.ProtoReflect.Descriptor instead.
func (*BSCountRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP(), []int{15}
}

func (x *BSCountRangeResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_internal_pb_protobuf_spec_bitset_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_bitset_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x62, 0x69, 0x74, 0x73,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x0f, 0x42, 0x53, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x42, 0x53, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x42, 0x53, 0x44, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x0d, 0x42, 0x53, 0x44, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x63, 0x0a, 0x11, 0x42, 0x53, 0x53, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x42, 0x53, 0x53, 0x65,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x42, 0x53, 0x4d, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x69, 0x74, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x42, 0x53, 0x4d, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x4d, 0x0a, 0x11, 0x42, 0x53, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x65, 0x6e, 0x64,
	0x22, 0x2c, 0x0a, 0x12, 0x42, 0x53, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x35,
	0x0a, 0x0d, 0x42, 0x53, 0x4d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x04, 0x62, 0x69, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x53, 0x4d, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x22, 0x0a, 0x0e, 0x42, 0x53, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x0f, 0x42, 0x53, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x13,
	0x42, 0x53, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x2c, 0x0a,
	0x14, 0x42, 0x53, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_bitset_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_bitset_proto_rawDescData = file_internal_pb_protobuf_spec_bitset_proto_rawDesc
)

func file_internal_pb_protobuf_spec_bitset_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_bitset_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_bitset_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_bitset_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_bitset_proto_rawDescData
}

var file_internal_pb_protobuf_spec_bitset_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_pb_protobuf_spec_bitset_proto_goTypes = []interface{}{
	(*BSCreateRequest)(nil),      // 0: proto.BSCreateRequest
	(*BSCreateResponse)(nil),     // 1: proto.BSCreateResponse
	(*BSDelRequest)(nil),         // 2: proto.BSDelRequest
	(*BSDelResponse)(nil),        // 3: proto.BSDelResponse
	(*BSSetRangeRequest)(nil),    // 4: proto.BSSetRangeRequest
	(*BSSetRangeResponse)(nil),   // 5: proto.BSSetRangeResponse
	(*BSMSetRequest)(nil),        // 6: proto.BSMSetRequest
	(*BSMSetResponse)(nil),       // 7: proto.BSMSetResponse
	(*BSGetRangeRequest)(nil),    // 8: proto.BSGetRangeRequest
	(*BSGetRangeResponse)(nil),   // 9: proto.BSGetRangeResponse
	(*BSMGetRequest)(nil),        // 10: proto.BSMGetRequest
	(*BSMGetResponse)(nil),       // 11: proto.BSMGetResponse
	(*BSCountRequest)(nil),       // 12: proto.BSCountRequest
	(*BSCountResponse)(nil),      // 13: proto.BSCountResponse
	(*BSCountRangeRequest)(nil),  // 14: proto.BSCountRangeRequest
	(*BSCountRangeResponse)(nil), // 15: proto.BSCountRangeResponse
}
var file_internal_pb_protobuf_spec_bitset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_bitset_proto_init() }
func file_internal_pb_protobuf_spec_bitset_proto_init() {
	if File_internal_pb_protobuf_spec_bitset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSSetRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSSetRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSMSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSMSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSGetRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSGetRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSMGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSMGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCountRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_bitset_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BSCountRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_bitset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_bitset_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_bitset_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_bitset_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_bitset_proto = out.File
	file_internal_pb_protobuf_spec_bitset_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_bitset_proto_goTypes = nil
	file_internal_pb_protobuf_spec_bitset_proto_depIdxs = nil
}
