// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/list.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LRPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LRPushRequest) Reset() {
	*x = LRPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRPushRequest) ProtoMessage() {}

func (x *LRPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRPushRequest.ProtoReflect.Descriptor instead.
func (*LRPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{0}
}

func (x *LRPushRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRPushRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LRPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LRPushResponse) Reset() {
	*x = LRPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRPushResponse) ProtoMessage() {}

func (x *LRPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRPushResponse.ProtoReflect.Descriptor instead.
func (*LRPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{1}
}

func (x *LRPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LLPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LLPushRequest) Reset() {
	*x = LLPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLPushRequest) ProtoMessage() {}

func (x *LLPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLPushRequest.ProtoReflect.Descriptor instead.
func (*LLPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{2}
}

func (x *LLPushRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LLPushRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LLPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LLPushResponse) Reset() {
	*x = LLPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLPushResponse) ProtoMessage() {}

func (x *LLPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLPushResponse.ProtoReflect.Descriptor instead.
func (*LLPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{3}
}

func (x *LLPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{4}
}

func (x *LPopRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LPopRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LPopResponse) Reset() {
	*x = LPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopResponse) ProtoMessage() {}

func (x *LPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopResponse.ProtoReflect.Descriptor instead.
func (*LPopResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{5}
}

func (x *LPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{6}
}

func (x *LRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LRangeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LRangeRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{7}
}

func (x *LRangeResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LExistRequest) Reset() {
	*x = LExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LExistRequest) ProtoMessage() {}

func (x *LExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LExistRequest.ProtoReflect.Descriptor instead.
func (*LExistRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{8}
}

func (x *LExistRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LExistRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type LExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists []bool `protobuf:"varint,1,rep,packed,name=exists,proto3" json:"exists,omitempty"`
}

func (x *LExistResponse) Reset() {
	*x = LExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LExistResponse) ProtoMessage() {}

func (x *LExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LExistResponse.ProtoReflect.Descriptor instead.
func (*LExistResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{9}
}

func (x *LExistResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type LDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LDelRequest) Reset() {
	*x = LDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LDelRequest) ProtoMessage() {}

func (x *LDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LDelRequest.ProtoReflect.Descriptor instead.
func (*LDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{10}
}

func (x *LDelRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LDelResponse) Reset() {
	*x = LDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LDelResponse) ProtoMessage() {}

func (x *LDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LDelResponse.ProtoReflect.Descriptor instead.
func (*LDelResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{11}
}

func (x *LDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LCountRequest) Reset() {
	*x = LCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LCountRequest) ProtoMessage() {}

func (x *LCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LCountRequest.ProtoReflect.Descriptor instead.
func (*LCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{12}
}

func (x *LCountRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LCountResponse) Reset() {
	*x = LCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LCountResponse) ProtoMessage() {}

func (x *LCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LCountResponse.ProtoReflect.Descriptor instead.
func (*LCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{13}
}

func (x *LCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LMembersRequest) Reset() {
	*x = LMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LMembersRequest) ProtoMessage() {}

func (x *LMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LMembersRequest.ProtoReflect.Descriptor instead.
func (*LMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{14}
}

func (x *LMembersRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LMembersResponse) Reset() {
	*x = LMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LMembersResponse) ProtoMessage() {}

func (x *LMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_list_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LMembersResponse.ProtoReflect.Descriptor instead.
func (*LMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_list_proto_rawDescGZIP(), []int{15}
}

func (x *LMembersResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_internal_pb_protobuf_spec_list_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_list_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a,
	0x0d, 0x4c, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x4c, 0x52, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x4c, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x2a, 0x0a, 0x0e, 0x4c, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x37, 0x0a, 0x0b, 0x4c,
	0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x4c, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4f,
	0x0a, 0x0d, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x28, 0x0a, 0x0e, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x4c, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x4c, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x1f,
	0x0a, 0x0b, 0x4c, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x28, 0x0a, 0x0c, 0x4c, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e,
	0x4c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x4c, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2a, 0x0a, 0x10, 0x4c, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_list_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_list_proto_rawDescData = file_internal_pb_protobuf_spec_list_proto_rawDesc
)

func file_internal_pb_protobuf_spec_list_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_list_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_list_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_list_proto_rawDescData
}

var file_internal_pb_protobuf_spec_list_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_pb_protobuf_spec_list_proto_goTypes = []interface{}{
	(*LRPushRequest)(nil),    // 0: proto.LRPushRequest
	(*LRPushResponse)(nil),   // 1: proto.LRPushResponse
	(*LLPushRequest)(nil),    // 2: proto.LLPushRequest
	(*LLPushResponse)(nil),   // 3: proto.LLPushResponse
	(*LPopRequest)(nil),      // 4: proto.LPopRequest
	(*LPopResponse)(nil),     // 5: proto.LPopResponse
	(*LRangeRequest)(nil),    // 6: proto.LRangeRequest
	(*LRangeResponse)(nil),   // 7: proto.LRangeResponse
	(*LExistRequest)(nil),    // 8: proto.LExistRequest
	(*LExistResponse)(nil),   // 9: proto.LExistResponse
	(*LDelRequest)(nil),      // 10: proto.LDelRequest
	(*LDelResponse)(nil),     // 11: proto.LDelResponse
	(*LCountRequest)(nil),    // 12: proto.LCountRequest
	(*LCountResponse)(nil),   // 13: proto.LCountResponse
	(*LMembersRequest)(nil),  // 14: proto.LMembersRequest
	(*LMembersResponse)(nil), // 15: proto.LMembersResponse
}
var file_internal_pb_protobuf_spec_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_list_proto_init() }
func file_internal_pb_protobuf_spec_list_proto_init() {
	if File_internal_pb_protobuf_spec_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_list_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_list_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_list_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_list_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_list_proto = out.File
	file_internal_pb_protobuf_spec_list_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_list_proto_goTypes = nil
	file_internal_pb_protobuf_spec_list_proto_depIdxs = nil
}
