// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/map.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Pair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Pairs []*Pair `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *MPushRequest) Reset() {
	*x = MPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPushRequest) ProtoMessage() {}

func (x *MPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPushRequest.ProtoReflect.Descriptor instead.
func (*MPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{1}
}

func (x *MPushRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MPushRequest) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type MPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MPushResponse) Reset() {
	*x = MPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPushResponse) ProtoMessage() {}

func (x *MPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPushResponse.ProtoReflect.Descriptor instead.
func (*MPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{2}
}

func (x *MPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Keys [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *MPopRequest) Reset() {
	*x = MPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPopRequest) ProtoMessage() {}

func (x *MPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPopRequest.ProtoReflect.Descriptor instead.
func (*MPopRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{3}
}

func (x *MPopRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MPopRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MPopResponse) Reset() {
	*x = MPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPopResponse) ProtoMessage() {}

func (x *MPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPopResponse.ProtoReflect.Descriptor instead.
func (*MPopResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{4}
}

func (x *MPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Keys [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *MExistRequest) Reset() {
	*x = MExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MExistRequest) ProtoMessage() {}

func (x *MExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MExistRequest.ProtoReflect.Descriptor instead.
func (*MExistRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{5}
}

func (x *MExistRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MExistRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type MExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists []bool `protobuf:"varint,1,rep,packed,name=exists,proto3" json:"exists,omitempty"`
}

func (x *MExistResponse) Reset() {
	*x = MExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MExistResponse) ProtoMessage() {}

func (x *MExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MExistResponse.ProtoReflect.Descriptor instead.
func (*MExistResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{6}
}

func (x *MExistResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type MDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MDelRequest) Reset() {
	*x = MDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDelRequest) ProtoMessage() {}

func (x *MDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDelRequest.ProtoReflect.Descriptor instead.
func (*MDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{7}
}

func (x *MDelRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type MDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MDelResponse) Reset() {
	*x = MDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDelResponse) ProtoMessage() {}

func (x *MDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDelResponse.ProtoReflect.Descriptor instead.
func (*MDelResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{8}
}

func (x *MDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MCountRequest) Reset() {
	*x = MCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCountRequest) ProtoMessage() {}

func (x *MCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCountRequest.ProtoReflect.Descriptor instead.
func (*MCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{9}
}

func (x *MCountRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type MCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *MCountResponse) Reset() {
	*x = MCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCountResponse) ProtoMessage() {}

func (x *MCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCountResponse.ProtoReflect.Descriptor instead.
func (*MCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{10}
}

func (x *MCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MMembersRequest) Reset() {
	*x = MMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMembersRequest) ProtoMessage() {}

func (x *MMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMembersRequest.ProtoReflect.Descriptor instead.
func (*MMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{11}
}

func (x *MMembersRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type MMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *MMembersResponse) Reset() {
	*x = MMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMembersResponse) ProtoMessage() {}

func (x *MMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_map_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMembersResponse.ProtoReflect.Descriptor instead.
func (*MMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_map_proto_rawDescGZIP(), []int{12}
}

func (x *MMembersResponse) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_internal_pb_protobuf_spec_map_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_map_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6d, 0x61, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x04,
	0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x0c,
	0x4d, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72,
	0x73, 0x22, 0x29, 0x0a, 0x0d, 0x4d, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x0b,
	0x4d, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x22, 0x28, 0x0a, 0x0c, 0x4d, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x4d,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x4d, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0b,
	0x4d, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x28, 0x0a,
	0x0c, 0x4d, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x4d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x4d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x10, 0x4d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x70,
	0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x42, 0x0d,
	0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_map_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_map_proto_rawDescData = file_internal_pb_protobuf_spec_map_proto_rawDesc
)

func file_internal_pb_protobuf_spec_map_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_map_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_map_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_map_proto_rawDescData
}

var file_internal_pb_protobuf_spec_map_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_pb_protobuf_spec_map_proto_goTypes = []interface{}{
	(*Pair)(nil),             // 0: proto.Pair
	(*MPushRequest)(nil),     // 1: proto.MPushRequest
	(*MPushResponse)(nil),    // 2: proto.MPushResponse
	(*MPopRequest)(nil),      // 3: proto.MPopRequest
	(*MPopResponse)(nil),     // 4: proto.MPopResponse
	(*MExistRequest)(nil),    // 5: proto.MExistRequest
	(*MExistResponse)(nil),   // 6: proto.MExistResponse
	(*MDelRequest)(nil),      // 7: proto.MDelRequest
	(*MDelResponse)(nil),     // 8: proto.MDelResponse
	(*MCountRequest)(nil),    // 9: proto.MCountRequest
	(*MCountResponse)(nil),   // 10: proto.MCountResponse
	(*MMembersRequest)(nil),  // 11: proto.MMembersRequest
	(*MMembersResponse)(nil), // 12: proto.MMembersResponse
}
var file_internal_pb_protobuf_spec_map_proto_depIdxs = []int32{
	0, // 0: proto.MPushRequest.pairs:type_name -> proto.Pair
	0, // 1: proto.MMembersResponse.pairs:type_name -> proto.Pair
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_map_proto_init() }
func file_internal_pb_protobuf_spec_map_proto_init() {
	if File_internal_pb_protobuf_spec_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_map_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_map_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_map_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_map_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_map_proto = out.File
	file_internal_pb_protobuf_spec_map_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_map_proto_goTypes = nil
	file_internal_pb_protobuf_spec_map_proto_depIdxs = nil
}
