// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/row.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType DataType `protobuf:"varint,1,opt,name=dataType,proto3,enum=proto.DataType" json:"dataType,omitempty"`
	Key      []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Id       []byte   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Indexes  []*Index `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	Value    []byte   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_row_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_row_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_row_proto_rawDescGZIP(), []int{0}
}

func (x *Row) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_STRING
}

func (x *Row) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Row) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Row) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *Row) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_internal_pb_protobuf_spec_row_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_row_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x72, 0x6f, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70,
	0x65, 0x63, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92,
	0x01, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x2b, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_row_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_row_proto_rawDescData = file_internal_pb_protobuf_spec_row_proto_rawDesc
)

func file_internal_pb_protobuf_spec_row_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_row_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_row_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_row_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_row_proto_rawDescData
}

var file_internal_pb_protobuf_spec_row_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_pb_protobuf_spec_row_proto_goTypes = []interface{}{
	(*Row)(nil),   // 0: proto.Row
	(DataType)(0), // 1: proto.DataType
	(*Index)(nil), // 2: proto.Index
}
var file_internal_pb_protobuf_spec_row_proto_depIdxs = []int32{
	1, // 0: proto.Row.dataType:type_name -> proto.DataType
	2, // 1: proto.Row.indexes:type_name -> proto.Index
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_row_proto_init() }
func file_internal_pb_protobuf_spec_row_proto_init() {
	if File_internal_pb_protobuf_spec_row_proto != nil {
		return
	}
	file_internal_pb_protobuf_spec_data_type_proto_init()
	file_internal_pb_protobuf_spec_index_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_row_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_row_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_row_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_row_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_row_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_row_proto = out.File
	file_internal_pb_protobuf_spec_row_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_row_proto_goTypes = nil
	file_internal_pb_protobuf_spec_row_proto_depIdxs = nil
}
