// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/set.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SPushRequest) Reset() {
	*x = SPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPushRequest) ProtoMessage() {}

func (x *SPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPushRequest.ProtoReflect.Descriptor instead.
func (*SPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{0}
}

func (x *SPushRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SPushRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SPushResponse) Reset() {
	*x = SPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPushResponse) ProtoMessage() {}

func (x *SPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPushResponse.ProtoReflect.Descriptor instead.
func (*SPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{1}
}

func (x *SPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SPopRequest) Reset() {
	*x = SPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPopRequest) ProtoMessage() {}

func (x *SPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPopRequest.ProtoReflect.Descriptor instead.
func (*SPopRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{2}
}

func (x *SPopRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SPopRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SPopResponse) Reset() {
	*x = SPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPopResponse) ProtoMessage() {}

func (x *SPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPopResponse.ProtoReflect.Descriptor instead.
func (*SPopResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{3}
}

func (x *SPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SExistRequest) Reset() {
	*x = SExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SExistRequest) ProtoMessage() {}

func (x *SExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SExistRequest.ProtoReflect.Descriptor instead.
func (*SExistRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{4}
}

func (x *SExistRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SExistRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists []bool `protobuf:"varint,1,rep,packed,name=exists,proto3" json:"exists,omitempty"`
}

func (x *SExistResponse) Reset() {
	*x = SExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SExistResponse) ProtoMessage() {}

func (x *SExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SExistResponse.ProtoReflect.Descriptor instead.
func (*SExistResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{5}
}

func (x *SExistResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type SDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SDelRequest) Reset() {
	*x = SDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDelRequest) ProtoMessage() {}

func (x *SDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDelRequest.ProtoReflect.Descriptor instead.
func (*SDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{6}
}

func (x *SDelRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SDelResponse) Reset() {
	*x = SDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDelResponse) ProtoMessage() {}

func (x *SDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDelResponse.ProtoReflect.Descriptor instead.
func (*SDelResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{7}
}

func (x *SDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SCountRequest) Reset() {
	*x = SCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCountRequest) ProtoMessage() {}

func (x *SCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCountRequest.ProtoReflect.Descriptor instead.
func (*SCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{8}
}

func (x *SCountRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SCountResponse) Reset() {
	*x = SCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCountResponse) ProtoMessage() {}

func (x *SCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCountResponse.ProtoReflect.Descriptor instead.
func (*SCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{9}
}

func (x *SCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{10}
}

func (x *SMembersRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_set_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_set_proto_rawDescGZIP(), []int{11}
}

func (x *SMembersResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_internal_pb_protobuf_spec_set_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_set_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x73, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0c,
	0x53, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x50,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x53, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x28, 0x0a, 0x0e, 0x53, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x44, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x44,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x23, 0x0a, 0x0f, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_set_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_set_proto_rawDescData = file_internal_pb_protobuf_spec_set_proto_rawDesc
)

func file_internal_pb_protobuf_spec_set_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_set_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_set_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_set_proto_rawDescData
}

var file_internal_pb_protobuf_spec_set_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_pb_protobuf_spec_set_proto_goTypes = []interface{}{
	(*SPushRequest)(nil),     // 0: proto.SPushRequest
	(*SPushResponse)(nil),    // 1: proto.SPushResponse
	(*SPopRequest)(nil),      // 2: proto.SPopRequest
	(*SPopResponse)(nil),     // 3: proto.SPopResponse
	(*SExistRequest)(nil),    // 4: proto.SExistRequest
	(*SExistResponse)(nil),   // 5: proto.SExistResponse
	(*SDelRequest)(nil),      // 6: proto.SDelRequest
	(*SDelResponse)(nil),     // 7: proto.SDelResponse
	(*SCountRequest)(nil),    // 8: proto.SCountRequest
	(*SCountResponse)(nil),   // 9: proto.SCountResponse
	(*SMembersRequest)(nil),  // 10: proto.SMembersRequest
	(*SMembersResponse)(nil), // 11: proto.SMembersResponse
}
var file_internal_pb_protobuf_spec_set_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_set_proto_init() }
func file_internal_pb_protobuf_spec_set_proto_init() {
	if File_internal_pb_protobuf_spec_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_set_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_set_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_set_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_set_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_set_proto = out.File
	file_internal_pb_protobuf_spec_set_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_set_proto_goTypes = nil
	file_internal_pb_protobuf_spec_set_proto_depIdxs = nil
}
