// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: internal/pb/protobuf-spec/sorted_set.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Score float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{0}
}

func (x *Tuple) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Tuple) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ZPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Tuples []*Tuple `protobuf:"bytes,2,rep,name=tuples,proto3" json:"tuples,omitempty"`
}

func (x *ZPushRequest) Reset() {
	*x = ZPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPushRequest) ProtoMessage() {}

func (x *ZPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPushRequest.ProtoReflect.Descriptor instead.
func (*ZPushRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{1}
}

func (x *ZPushRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZPushRequest) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

type ZPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ZPushResponse) Reset() {
	*x = ZPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPushResponse) ProtoMessage() {}

func (x *ZPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPushResponse.ProtoReflect.Descriptor instead.
func (*ZPushResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{2}
}

func (x *ZPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ZPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ZPopRequest) Reset() {
	*x = ZPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPopRequest) ProtoMessage() {}

func (x *ZPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPopRequest.ProtoReflect.Descriptor instead.
func (*ZPopRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{3}
}

func (x *ZPopRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZPopRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type ZPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ZPopResponse) Reset() {
	*x = ZPopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPopResponse) ProtoMessage() {}

func (x *ZPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPopResponse.ProtoReflect.Descriptor instead.
func (*ZPopResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{4}
}

func (x *ZPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ZRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ZRangeRequest) Reset() {
	*x = ZRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeRequest) ProtoMessage() {}

func (x *ZRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeRequest.ProtoReflect.Descriptor instead.
func (*ZRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{5}
}

func (x *ZRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZRangeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ZRangeRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ZRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuples []*Tuple `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
}

func (x *ZRangeResponse) Reset() {
	*x = ZRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRangeResponse) ProtoMessage() {}

func (x *ZRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRangeResponse.ProtoReflect.Descriptor instead.
func (*ZRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{6}
}

func (x *ZRangeResponse) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

type ZExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ZExistRequest) Reset() {
	*x = ZExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZExistRequest) ProtoMessage() {}

func (x *ZExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZExistRequest.ProtoReflect.Descriptor instead.
func (*ZExistRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{7}
}

func (x *ZExistRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ZExistRequest) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type ZExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists []bool `protobuf:"varint,1,rep,packed,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ZExistResponse) Reset() {
	*x = ZExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZExistResponse) ProtoMessage() {}

func (x *ZExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZExistResponse.ProtoReflect.Descriptor instead.
func (*ZExistResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{8}
}

func (x *ZExistResponse) GetExists() []bool {
	if x != nil {
		return x.Exists
	}
	return nil
}

type ZDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZDelRequest) Reset() {
	*x = ZDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZDelRequest) ProtoMessage() {}

func (x *ZDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZDelRequest.ProtoReflect.Descriptor instead.
func (*ZDelRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{9}
}

func (x *ZDelRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ZDelResponse) Reset() {
	*x = ZDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZDelResponse) ProtoMessage() {}

func (x *ZDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZDelResponse.ProtoReflect.Descriptor instead.
func (*ZDelResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{10}
}

func (x *ZDelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ZCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZCountRequest) Reset() {
	*x = ZCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCountRequest) ProtoMessage() {}

func (x *ZCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCountRequest.ProtoReflect.Descriptor instead.
func (*ZCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{11}
}

func (x *ZCountRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ZCountResponse) Reset() {
	*x = ZCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCountResponse) ProtoMessage() {}

func (x *ZCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCountResponse.ProtoReflect.Descriptor instead.
func (*ZCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{12}
}

func (x *ZCountResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ZMembersRequest) Reset() {
	*x = ZMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZMembersRequest) ProtoMessage() {}

func (x *ZMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZMembersRequest.ProtoReflect.Descriptor instead.
func (*ZMembersRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{13}
}

func (x *ZMembersRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ZMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuples []*Tuple `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
}

func (x *ZMembersResponse) Reset() {
	*x = ZMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZMembersResponse) ProtoMessage() {}

func (x *ZMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZMembersResponse.ProtoReflect.Descriptor instead.
func (*ZMembersResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP(), []int{14}
}

func (x *ZMembersResponse) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

var File_internal_pb_protobuf_spec_sorted_set_proto protoreflect.FileDescriptor

var file_internal_pb_protobuf_spec_sorted_set_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x73, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x05, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x5a, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x75,
	0x70, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73,
	0x22, 0x29, 0x0a, 0x0d, 0x5a, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x37, 0x0a, 0x0b, 0x5a,
	0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x5a, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4f,
	0x0a, 0x0d, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x36, 0x0a, 0x0e, 0x5a, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52,
	0x06, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x5a, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x5a, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x0b,
	0x5a, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x28, 0x0a,
	0x0c, 0x5a, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0d, 0x5a, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x5a, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x5a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x10, 0x5a, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x74,
	0x75, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x06, 0x74, 0x75, 0x70, 0x6c, 0x65,
	0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_protobuf_spec_sorted_set_proto_rawDescOnce sync.Once
	file_internal_pb_protobuf_spec_sorted_set_proto_rawDescData = file_internal_pb_protobuf_spec_sorted_set_proto_rawDesc
)

func file_internal_pb_protobuf_spec_sorted_set_proto_rawDescGZIP() []byte {
	file_internal_pb_protobuf_spec_sorted_set_proto_rawDescOnce.Do(func() {
		file_internal_pb_protobuf_spec_sorted_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_protobuf_spec_sorted_set_proto_rawDescData)
	})
	return file_internal_pb_protobuf_spec_sorted_set_proto_rawDescData
}

var file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_pb_protobuf_spec_sorted_set_proto_goTypes = []interface{}{
	(*Tuple)(nil),            // 0: proto.Tuple
	(*ZPushRequest)(nil),     // 1: proto.ZPushRequest
	(*ZPushResponse)(nil),    // 2: proto.ZPushResponse
	(*ZPopRequest)(nil),      // 3: proto.ZPopRequest
	(*ZPopResponse)(nil),     // 4: proto.ZPopResponse
	(*ZRangeRequest)(nil),    // 5: proto.ZRangeRequest
	(*ZRangeResponse)(nil),   // 6: proto.ZRangeResponse
	(*ZExistRequest)(nil),    // 7: proto.ZExistRequest
	(*ZExistResponse)(nil),   // 8: proto.ZExistResponse
	(*ZDelRequest)(nil),      // 9: proto.ZDelRequest
	(*ZDelResponse)(nil),     // 10: proto.ZDelResponse
	(*ZCountRequest)(nil),    // 11: proto.ZCountRequest
	(*ZCountResponse)(nil),   // 12: proto.ZCountResponse
	(*ZMembersRequest)(nil),  // 13: proto.ZMembersRequest
	(*ZMembersResponse)(nil), // 14: proto.ZMembersResponse
}
var file_internal_pb_protobuf_spec_sorted_set_proto_depIdxs = []int32{
	0, // 0: proto.ZPushRequest.tuples:type_name -> proto.Tuple
	0, // 1: proto.ZRangeResponse.tuples:type_name -> proto.Tuple
	0, // 2: proto.ZMembersResponse.tuples:type_name -> proto.Tuple
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_pb_protobuf_spec_sorted_set_proto_init() }
func file_internal_pb_protobuf_spec_sorted_set_proto_init() {
	if File_internal_pb_protobuf_spec_sorted_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZPopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_protobuf_spec_sorted_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_protobuf_spec_sorted_set_proto_goTypes,
		DependencyIndexes: file_internal_pb_protobuf_spec_sorted_set_proto_depIdxs,
		MessageInfos:      file_internal_pb_protobuf_spec_sorted_set_proto_msgTypes,
	}.Build()
	File_internal_pb_protobuf_spec_sorted_set_proto = out.File
	file_internal_pb_protobuf_spec_sorted_set_proto_rawDesc = nil
	file_internal_pb_protobuf_spec_sorted_set_proto_goTypes = nil
	file_internal_pb_protobuf_spec_sorted_set_proto_depIdxs = nil
}
