{
 "title": "SDB",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "15s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "SDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) /\nsum(rate(grpc_server_handled_total{grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "success rate"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{grpc_code=\"OK\"}[$interval])) by (grpc_method) / sum(irate(grpc_server_handled_total{}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{grpc_type=\"unary\"}[$interval])) by (grpc_method) ",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{}[$interval])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "resident"
    },
    { "expr": "process_virtual_memory_bytes{}", "legendFormat": "virtual" }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds{}", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_byte", "legendFormat": "bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{}[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{}",
     "legendFormat": "stack inuse"
    },
    { "expr": "go_memstats_heap_inuse_bytes{}", "legendFormat": "heap inuse" }
   ]
  }
 ]
}