name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install protoc-gen-go
        run: |
          go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway
          go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Build Protobuf
        run: sh ./scripts/build_protobuf.sh

      - name: Build
        run:
          go build -o sdb -v ./cmd/sdb/sdb.go